### ISSUE TITLE
Direction of properties (in general) and the role of their inverse

### ISSUE THREAD

**Issue by pierrechoffe** [DOREMUS-ANR/doremus-ontology#20] opened 2016-09-27 13:39 UTC
(from[ issue in marc2rdf](https://github.com/DOREMUS-ANR/marc2rdf/issues/17#issuecomment-249863171))
Raphaël : We may argue on the direction of the properties though

**Comment by rtroncy** [comment] 2016-09-27 13:44
You will need to be more specific for describing this issue as there is no general solution. For which properties would you like to discuss their direction? Bringing concrete and real examples would be a plus to understand the issue.

**Comment by pierrechoffe** [comment] 2016-09-27 14:33
@rtroncy i grok the general idea : put ourselves in the shoes of the users, thinking of their possible requests, in order to determine which direction would be more logical.

In the case of the Awards, we can assume the user would want to know what awards a CD received, so this would translate as a request on F24_Publication_Expression _uxx_was_attributed_by_ M39_Award_Assignment _uyy_assigned_ M36_Award

Am I wrong to add that the point is also that we do *not* want to have inverse properties. If we did, and assuming we used the generic p140 & p141, we could just as well use the inverse of p140, _p140i_was_attributed_by_ instead of _uxx_was_assigned_by_ ?

**Comment by pierrechoffe** [comment] 2016-09-27 14:43
Question 1 : do we need to create specific properties or can we use the generic _p140_assigned_attribute_ and _p141_assigned_ ? In FRBRoo they systematically created new properties with specific domain and range.

Question 2 : A user could also want to know which publications received awards in 2016. In this case, the path would be : M36_Award _uzz_was_assigned_by_ M39_Award Assignment _uww_assigned_attribute_to_ F24.
So, for the same concepts, we can have requests in both directions (from F24 to M36 or from M36 to F24) : what awards did this CD receive ? What CDs received this award in 2016 ?

So, it is difficult to answer your question. Regarding Award Assignment at least, I cannot see any clear answer. The answer may be clearer regarding Identifier Assignment.

Now another question : 

Question 4 : if we extend the general idea to existing relations (in CRM & FRBRoo), we might have to change things a bit. Regarding Assignments, things are modeled this way : 
(something) <---(assigned)--- E13_Attribute_Assignment ---(assigned to)---> (something)
therefore one property direction will always have to be reversed if we want to have : 
(something) ------> E13 ------> (something)
For example : as for now, if I want to know the expected duration of a musical piece ("durée éditeur"), the path should be F22 _p39i_was_measured_by_ E16_Measurement _p40_measured_ E54_Dimension.
This implied using the inverse p39i. 
I would argue that in this case also, one may want to know the duration of a piece, but also which pieces have a duration of 10 minutes.

So it is really difficult to answer your question.

**Comment by rtroncy** [comment] 2016-09-27 15:18
>  i grok the general idea : put ourselves in the shoes of the users

"Users" is often undefined. Let's say someone who will re-use the data that the institutions will publish. We call them data consumers.

> In the case of the Awards, we can assume the user would want to know what awards a CD received.

Who is "we"? The best would be to ask the people who are really skilled to provide answers to those questions ... and they are even partner in the project: Gériico :-)
For a given CD, you may indeed want to get the awards it has received. Conversely, for a given award type, you may want to get all the CDs that have been laureate.

> Am I wrong to add that the point is also that we do not want to have inverse properties.

You're wrong, as this has already been discussed in #2

**Comment by rtroncy** [comment] 2016-09-27 15:23
> Question 1 

(real) example ... please !

> Question 2

You don't have to make a choice, if both are useful. Again, I don't understand what specific issue you're describing and how is this related to the very generic title you give to this issue? Are you reviving #2?

There is no question 3 ... was it for checking that I'm reading well? :-)

> Question 4

Again, I don't see what is the specific issue you want to point out. There are plenty of cases in the wild where both directions are useful to have. So what?

**Comment by pierrechoffe** [comment] 2016-09-27 15:45
>You don't have to make a choice, if both are useful.

Maybe this was the point I misunderstood in your initial answer. My answer would have been easy : what awards did this CD receive ? What CDs received this award in 2016 ? no choice to make.

But ok, the important thing is to keep this idea in mind, should we have a case where the choice is obvious.

**Comment by rtroncy** [comment] 2016-09-27 15:53
So, I propose to close this issue as an obvious duplicate of #2 :-) Or did you have other doubts?

**Comment by pierrechoffe** [comment] 2016-09-27 15:56
nope, I think this is clear :smile:

**Comment by rtroncy** [comment] 2016-09-27 15:59
Renaming the issue for proper search and closing, as duplicate but complementary discussion to #2.

**Closed by rtroncy** 2016-09-27 15:59 UTC

**Comment by delahousse** [comment] 2016-09-28 08:09
Hello,

Just a return of experience from other projects:

It can be a good rule to have the initial property in the direction where
you change a minimum of other resources. For example with frbr it s better
to declare the link from manifestation to expression so when you add a new
manifestation you don't have to make an update on the expression, the
property in the other way will not be declared or infered.

The rule would be to declare first the link going to other resources, for
the classes of resources which depend on other resources.
(my example was a lot easier to understand, declare the properties going
out of manifestation to expression, then the properties going out of
expression to work)

bonne journée
Jean

Jean Delahousse

Independent Consultant
Semantic technologies, Linked Open Data
https://fr.linkedin.com/in/jeandelahousse
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55
skype jean.delahousse

2016-09-27 17:56 GMT+02:00 Pierre Choffé <notifications@github.com>:
